### ISSUE TITLE
When will perfUtils be released?

### ISSUE THREAD

**Issue by mogar** [nasa/perfutils-java#1]
Is this still going to be released?

**Comment by skliper** [comment]
@tngo67 may know?  See also https://github.com/OpenSatKit/OpenSatKit/tree/master/cfs/tools/perfutils-java.

**Comment by mogar** [comment]
I haven't been able to get that working. I opened up an issue on it here: https://github.com/OpenSatKit/OpenSatKit/issues/65

Is that perfutils version the same as the one that would be open sourced here?

**Comment by mogar** [comment]
Apparently this is the one to use: https://github.com/OpenSatKit/OpenSatKit/tree/master/cosmos/cfs_kit/tools/perf-monitor
